merge in to checkmarx.yaml (#3)
Add localsca scanning mode.

diff --git a/.github/workflows/checkmarx.yaml b/.github/workflows/checkmarx.yaml
--- a/.github/workflows/checkmarx.yaml
+++ b/.github/workflows/checkmarx.yaml
@@ -31,13 +31,28 @@ on:
         required: false
         type: string
         default: --cx-flow.filterSeverity --cx-flow.filterCategory --cx-flow.thresholds.high=0 --cx-flow.thresholds.medium=0 --cx-flow.thresholds.low=0 --sca.thresholds-score=11
+      localsca:
+        required: false
+        type: boolean
+        default: false
       params:
         required: false
         type: string
+      scala_java_version:
+        required: false
+        type: string
+        default: adopt@1.8
+      sca_params:
+        required: false
+        type: string
+      sca_log_level:
+        required: false
+        type: string
+        default: Verbose
 
 
 jobs:
-  test:
+  checkmarx:
     name: Checkmarx
     runs-on: [self-hosted]
     concurrency:
@@ -48,27 +63,31 @@ jobs:
         with:
           ref: ${{ github.event.client_payload.pull_request.head.sha }}
 
-      - name: Verify environment
+      - name: Verify and configure environment
+        id: setup_env
         run: |
           if [ "${{ vars.CHECKMARX_TEAM }}" == '' ]; then echo "Error: CHECKMARX_TEAM was not set"; exit 1; fi
           echo "${{ vars.CHECKMARX_TEAM }}"
+          projname=$(echo ${{ inputs.project }} | tr / -); echo "projname=$projname" >> $GITHUB_OUTPUT
+          if [[ "${{ inputs.params }}" =~ "include-sources=true" ]];then
+            echo "Using checkmarx's github token"
+            echo "github_token=${{ secrets.CHECKMARX_GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
+          else
+            echo "Using default github token"
+            echo "github_token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
+          fi
+          if [[ "${{ inputs.localsca }}" == "true" ]];then
+            echo "localsca==true, so force scanners=sast"
+            echo "scanners=sast" >> $GITHUB_OUTPUT
+          else
+            echo "localsca==false, so pass through scanners"
+            echo "scanners=${{ inputs.scanners }}" >> $GITHUB_OUTPUT
+          fi
 
       - name: Remove unneeded files
         run: |
           rm -rf db spec script/data_migrations ./public/images/seconds_animated_60.gif test tests
           find . -name __tests__ -o -name __mocks__ -print0 | xargs -0 rm -rf
-          if test -f Pipfile.lock;then jq -r '.default | to_entries[] | .key + .value.version' Pipfile.lock > requirements.txt;fi
-
-      - name: Figure out Github Token
-        id: github_token
-        run: |
-          if [[ "${{ inputs.params }}" =~ "include-sources=true" ]];then
-            echo "Using checkmarx's github token"
-            echo "token=${{ secrets.CHECKMARX_GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
-          else
-            echo "Using default github token"
-            echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
-          fi
 
       - name: Checkmarx CxFlow Action
         uses: checkmarx-ts/checkmarx-cxflow-github-action@HEAD
@@ -83,9 +102,83 @@ jobs:
           sca_username: ${{ vars.CHECKMARX_SCA_USERNAME }}
           sca_tenant: ${{ vars.CHECKMARX_SCA_TENANT }}
           incremental: ${{ inputs.incremental }}
-          scanners: ${{ inputs.scanners }}
+          scanners: ${{ steps.setup_env.outputs.scanners }}
           break_build: ${{ inputs.break_build }}
           bug_tracker: ${{ inputs.bug_tracker }}
-          github_token: ${{ steps.github_token.outputs.token }}
+          github_token: ${{ steps.setup_env.outputs.github_token }}
           params: --sca.team=${{ vars.CHECKMARX_TEAM }} --namespace=${{ github.repository_owner }}  --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }} ${{ inputs.filter_params }} ${{ inputs.params }}
           java_opts: -Xmx4g
+
+  sca:
+    name: Checkmarx SCA local
+    if: ${{ inputs.localsca }}
+    runs-on: [self-hosted]
+    concurrency:
+      group: sca
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.client_payload.pull_request.head.sha }}
+
+      - name: Verify and configure environment
+        id: setup_env
+        run: |
+          if [ "${{ vars.CHECKMARX_TEAM }}" == '' ]; then echo "Error: CHECKMARX_TEAM was not set"; exit 1; fi
+          echo "${{ vars.CHECKMARX_TEAM }}"
+          projname=$(echo ${{ inputs.project }} | tr / -); echo "projname=$projname" >> $GITHUB_OUTPUT
+          test -f ./grafana/pyproject.toml && echo "build_poetry=true" >> $GITHUB_OUTPUT
+          test -f build.sbt && echo "build_sbt=true" >> $GITHUB_OUTPUT
+          echo "Environment complete."
+
+      - name: Remove unneeded files
+        run: |
+          rm -rf db spec script/data_migrations ./public/images/seconds_animated_60.gif test tests
+          find . -name __tests__ -o -name __mocks__ -print0 | xargs -0 rm -rf
+
+      - name: Setup Scala
+        if: steps.setup_env.outputs.build_sbt
+        uses: retentionscience/setup-scala@v14
+        with:
+          java-version: ${{ inputs.scala_java_version }}
+
+      - name: Setup Pyenv
+        if : steps.setup_env.outputs.build_poetry
+        id: setup-pyenv
+        uses: retentionscience/pyenv-action@v14
+      - name: Install poetry
+        if : steps.setup_env.outputs.build_poetry
+        id: setup-poetry
+        run: make -C grafana compile
+
+      - name: Install python virtualenv
+        run: |
+          if test -f Pipfile.lock;then jq -r '.default | to_entries[] | .key + .value.version' Pipfile.lock > requirements.txt;fi
+          python3 -m pip install virtualenv
+
+      - name: SCA Resolver
+        id: scaresolver
+        run: |
+            mkdir ${{ github.workspace }}/SCAResolver
+            wget --quiet "https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz"
+            tar -xvf ScaResolver-linux64.tar.gz -C ${{ github.workspace }}/SCAResolver
+            ${{ github.workspace }}/SCAResolver/ScaResolver -s ${{ github.workspace }} -n '${{ steps.setup_env.outputs.projname }}' -a '${{ vars.CHECKMARX_SCA_TENANT }}' -u '${{ vars.CHECKMARX_SCA_USERNAME }}' -p '${{ secrets.CHECKMARX_SCA_PASSWORD }}' -t '${{ vars.CHECKMARX_TEAM }}' --log-level '${{ inputs.sca_log_level }}' ${{ inputs.sca_params }} 2>&1 | tee scaresolver.log
+            comment=$(cat scaresolver.log | sed -n '/### Scan Summary ###/,/^Full report available at/p' | grep -v '####')
+            if [ -z "$comment" ];then
+               comment="***SCA Resolver has probably failed.***"
+            fi
+            echo 'sca-scan-summary<<EOF' >> $GITHUB_OUTPUT
+            echo "$comment" >> $GITHUB_OUTPUT
+            echo 'EOF' >> $GITHUB_OUTPUT
+            exit_code=${PIPESTATUS[0]}
+            exit $exit_code
+
+      - name: PR Decoration
+        if: always()
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          message: |
+            ![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)
+            **Checkmarx SCA - Scan Summary**
+            ${{ steps.scaresolver.outputs.sca-scan-summary }}
+          comment_tag: sca_resolver_decoration
